server:
  port: 9101
eureka:
  client:
    serviceUrl: #服务中心的ip和端口号和路径
      defaultZone: http://admin:123456@peer1:8761/eureka/,http://admin:123456@peer2:8762/eureka/

#服务的名称
spring:
  application:
    name: service-ribbon  #这个是以后提供给调用者的名字，只要调用改名字就可以自动访问到  服务的ip和端口号和路径
  #链路追踪
  zipkin:
    base-url: http://localhost:9411
ribbon:
#  MaxAutoRetries: 1 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
#  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
#  OkToRetryOnAllOperations: true # 对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的
  ConnectTimeout: 10000 #请求连接的超时时间
  ReadTimeout: 10000 #请求处理的超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

