eureka:
  client:
    serviceUrl: #服务中心的ip和端口号和路径
      defaultZone: http://admin:123456@peer1:8761/eureka/,http://admin:123456@peer2:8762/eureka/
server:
  port: 8888  #配置中心端口号

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liuhanyu_my_com/congif #远程仓库地址
          search-paths: config #分支下的文件名
          username:
          password:
      label: master  #所在分支名
      #配置中心的名称
  application:
    name: config-server
  # 链路追踪
  zipkin:
    base-url: http://localhost:9411
