server:
  port: 8762 #中心的端口号

eureka:
  instance:
    hostname: peer2 #中心的本地端口号
    #prefer-ip-address: true #使用ip地址向中心注册
    #ip-address: 192.168.50.98 #固定ip地址
  client:
    registerWithEureka: false #不注册(自己是中心)
    fetchRegistry: false   #不发现
    serviceUrl: #提供服务的url
      defaultZone: http://admin:123456@peer1:8761/eureka/

#服务的名称
spring:
  profiles: peer2
    #开启认证
  security:
    user:
      name: admin #登陆用户名
      password: 123456 #登陆密码
