server:
  port: 8761 #中心的端口号

eureka:
  instance:
    hostname: peer1    #高可用的中心#localhost #中心的本地端口号
    #prefer-ip-address: true #使用ip地址向中心注册
    #ip-address: 192.168.50.98 #固定ip地址
  client:
    registerWithEureka: false #不注册(自己是中心)
    fetchRegistry: false   #不发现
    serviceUrl: #提供服务的url
      defaultZone: http://admin:123456@peer2:8762/eureka/
##服务的名称
#spring:
#  application:
#    name: eureka-server
spring:
  profiles: peer1 #高可用的注册中心

    #开启认证
  security:
    user:
      name: admin #登陆用户名
      password: 123456 #登陆密码


