spring:
  profiles:
    active: peer1
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411


#按照官方文档的指示，需要改变etc/hosts，linux系统通过vim /etc/hosts ,加上：
  #127.0.0.1 peer1
  #127.0.0.1 peer2
  #windows电脑，在c:/windows/systems/drivers/etc/hosts 修改。
