server:
  port: 9201

eureka:
  client:
    serviceUrl: #服务中心的ip和端口号和路径
      defaultZone: http://admin:123456@localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: service-feign  #这个是以后提供给调用者的名字，只要调用改名字就可以自动访问到  服务的ip和端口号和路径
 #链路追踪
  zipkin:
    base-url: http://localhost:9411


#  #配置模板相关东西
#  thymeleaf:
#    suffix: .html
#    prefix: classpath:localhost:9301/templates/
#    check-template: true
#    encoding: utf-8
#    servlet:
#      content-type: text/html
#    cache: false
#
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
    #网管服务()


#开启熔断器
feign:
  hystrix:
    enabled: true

  httpclient:
    connection-timeout: 2000
    connection-timer-repeat: 3000


